In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent = ['the glass of mlik',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good',]

In [3]:
sent

['the glass of mlik',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
# define the vocabulary size
voc_size = 10000

In [8]:
#one hot represenation

one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[7958, 7353, 248, 1744],
 [7958, 7353, 248, 6170],
 [7958, 5328, 248, 3668],
 [4661, 6097, 4810, 4049, 7336],
 [4661, 6097, 4810, 4049, 1135],
 [8476, 7958, 3120, 248, 1067],
 [1774, 1299, 8944, 4049]]

In [43]:
#word embedding representations

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [44]:
import numpy as np


In [45]:
sent_length=8 # to make all sentences with equal number of words - pad_sequence
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
#embedded_docs=pad_sequences(one_hot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7958 7353  248 1744]
 [   0    0    0    0 7958 7353  248 6170]
 [   0    0    0    0 7958 5328  248 3668]
 [   0    0    0 4661 6097 4810 4049 7336]
 [   0    0    0 4661 6097 4810 4049 1135]
 [   0    0    0 8476 7958 3120  248 1067]
 [   0    0    0    0 1774 1299 8944 4049]]


In [46]:
#feature representation
dim=10


In [51]:

model = Sequential()
model.add(Embedding(voc_size,dim,8))
model.compile(optimizer='adam',loss='mse')


ValueError: Could not interpret initializer identifier: 8

In [50]:
model.summary()

Model: "sequential_16"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)